name: marketing_attribution
version: '1.0.0'
config-version: 2
profile: marketing_attribution
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  marketing_attribution:
    staging:
      +materialized: view
    marts:
      +materialized: table
